Use consistent var prefix

diff --git a/roles/nas/templates/backupusb b/roles/nas/templates/backupusb
--- a/roles/nas/templates/backupusb
+++ b/roles/nas/templates/backupusb
@@ -2,7 +2,7 @@
 
 set -e
 
-[[ ${EUID} -eq 0 ]] || { echo 'Must be run as root' >&2; exit 1; }
+[[ ${EUID} -eq 0 ]] || { echo 'Must be run as root'>&2; exit 1; }
 
 RETENTION="{{ nas_backup_directories_retention }}"
 
@@ -17,24 +17,22 @@ elif [[ $# -eq 0 ]]; then
     key_file="{{ nas_usb_key_file }}"
     backup_dir="{{ nas_backup_directory }}"
 else
-    echo "Usage: $(basename "${0}") backup /dev/usb /cryptsetup/key/file /media/nas/backups" >&2
+    echo "Usage: $(basename "${0}") backup /dev/usb /luks/key/file /media/nas/backups">&2
     exit 1
 fi
 
 mount_dir="$(mktemp -d)"
 
-is_mounted() {
+is_mapped() {
 	cryptsetup status ${name} >/dev/null
 }
 
-mount_luks() {
+open_luks() {
 	cryptsetup --key-file ${key_file} luksOpen ${device} ${name}
 }
 
-is_mounted || mount_luks || { echo 'Failed to mount luks device' >&2; exit 1; }
-mount \
-    -t ext4 /dev/mapper/${name} \
-    ${mount_dir}
+is_mapped || open_luks || { echo 'Failed to open luks device'>&2; exit 1; }
+mount -t ext4 /dev/mapper/${name} ${mount_dir}
 
 # eg. /tmp/tmp.xxx/backup.2018-12-30
 target_dir="${mount_dir}/$(date -d @$(stat --format=%Y "${backup_dir}") +backup.%Y-%m-%d)"
diff --git a/roles/nas/templates/mountnas b/roles/nas/templates/mountnas
--- a/roles/nas/templates/mountnas
+++ b/roles/nas/templates/mountnas
@@ -17,26 +17,26 @@ elif [[ $# -eq 0 ]]; then
     key_file="{{ nas_raid1_key_file }}"
     mount_dir="{{ nas_mount_directory }}"
 else
-    echo "Usage: $(basename "${0}") left /dev/sdb right /dev/sdc /cryptsetup/key/file /media/nas" >&2
+    echo "Usage: $(basename "${0}") left /dev/sda right /dev/sdb /luks/key/file /media/nas" >&2
     exit 1
 fi
 
-[[ ${EUID} -eq 0 ]] || { echo 'Must be run as root' >&2; exit 1; }
-[[ ! "$(ls -A "${mount_dir}")" ]] || { echo "${mount_dir} is not empty" >&2; exit; }
+[[ ${EUID} -eq 0 ]] || { echo 'Must be run as root'>&2; exit 1; }
+[[ ! "$(ls -A "${mount_dir}")" ]] || { echo "${mount_dir} is not empty">&2; exit 1; }
 
-is_mounted() {
+is_mapped() {
 	local name=$1
 	cryptsetup status ${name} >/dev/null
 }
 
-mount_luks() {
+open_luks() {
 	local name=$1
 	local device=$2
 	cryptsetup --key-file ${key_file} luksOpen ${device} ${name}
 }
 
-is_mounted ${name_left} || mount_luks ${name_left} ${device_left} || { echo 'Failed to mount luks device' >&2; exit 1; }
-is_mounted ${name_right} || mount_luks ${name_right} ${device_right} || { echo 'Failed to mount luks device' >&2; exit 1; }
+is_mapped ${name_left} || open_luks ${name_left} ${device_left} || { echo 'Failed to open luks device'>&2; exit 1; }
+is_mapped ${name_right} || open_luks ${name_right} ${device_right} || { echo 'Failed to open luks device'>&2; exit 1; }
 mount \
     -t btrfs /dev/mapper/${name_left} \
     -o device=/dev/mapper/${name_left},device=/dev/mapper/${name_right} \
